pool: MyAgentPool
variables:
  buildConfiguration: 'Release'
steps:
- bash: echo First Pipeline
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

